Repository bcgov/quickstart-openshift-backends, pull requests merged in 2023-09, with the labels that each got.

#13 feat: merge workflow
  .github/workflows/merge.yml
Labels: bug, enhancement

#12 docs: badges
  README.md
Labels: documentation

#14 ci: continue updating repo links and corrections
  .github/workflows/merge.yml
  README.md
  SECURITY.md
  backend-go/go.mod
  backend-go/main.go
  backend-go/openshift.deploy.yml
  backend-go/src/app.go
  backend-go/src/database/connections.go
  backend-go/src/v1/repositories/user-repository.go
  backend-go/src/v1/routes/user-routes.go
  backend-go/src/v1/services/user-service.go
  backend-java/README.md
  backend-java/openshift.deploy.yml
  backend-java/pom.xml
  backend-java/src/main/resources/META-INF/resources/index.html
  backend-py/openshift.deploy.yml
Labels: bug, chore

#15 ci: clip triggers from merge workflow
  .github/workflows/merge.yml
Labels: bug

#21 deps: bump deployer action
  .github/workflows/merge.yml
  .github/workflows/pr-open.yml
Labels: dependencies

#20 change order to avoid log noise of healthchecks
  backend-go/src/app.go
Labels: chore

#23 deps: quarkus graalvmce build base
  backend-java/.dockerignore
  backend-java/Dockerfile
Labels: dependencies

#24 Java 21
  backend-java/Dockerfile
Labels: enhancement

#25 feat: general cleanup, flyway consistency
  backend-py/db/migrations/V1.0.0__init.sql
  backend-py/src/v1/models/entities.py
  backend-py/src/v1/models/model.py
Labels: chore
